name: Deploy to Minikube

on:
  push:
    branches:
      - '*'  # Trigger the workflow on pushes to any branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install kubectl to interact with Kubernetes
      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      # Step 3: Install Minikube on the GitHub runner
      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      # Step 4: Start Minikube on the GitHub runner (using Docker as the driver)
      - name: Start Minikube
        run: |
          minikube start --driver=docker

      # Step 5: Set up the Kubernetes environment (for Minikube)
      - name: Set up kubectl config
        run: |
          mkdir -p $HOME/.kube
          cp -r $(minikube kubeconfig) $HOME/.kube/config
          kubectl config use-context minikube

      # Step 6: Deploy the Job to Minikube Kubernetes cluster
      - name: Deploy Kubernetes Job
        run: |
          kubectl apply -f k8s/job.yaml
          kubectl get jobs

      # Step 7: Wait for the Job to complete (with a 10-minute timeout)
      - name: Wait for Job to complete
        run: |
          kubectl wait --for=condition=complete job/ci-job --timeout=600s
          kubectl logs job/ci-job
